// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-5nu6g8-3he9KnhTi5riXe0fnMZSDbEk',
    appId: '1:662979389508:web:48c795d8e0e6a57beb7411',
    messagingSenderId: '662979389508',
    projectId: 'doanckuddddnt',
    authDomain: 'doanckuddddnt.firebaseapp.com',
    storageBucket: 'doanckuddddnt.firebasestorage.app',
    measurementId: 'G-FRHHNXDQS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCskwzW_WQtFx5EQTQ-6iLlZU3UEaxjvCY',
    appId: '1:662979389508:android:41c505f58c02a871eb7411',
    messagingSenderId: '662979389508',
    projectId: 'doanckuddddnt',
    storageBucket: 'doanckuddddnt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD07G95zw-SJ_12TNasN-2sG774NMYQxxQ',
    appId: '1:662979389508:ios:4684e577d3348c9feb7411',
    messagingSenderId: '662979389508',
    projectId: 'doanckuddddnt',
    storageBucket: 'doanckuddddnt.firebasestorage.app',
    iosBundleId: 'com.example.doancuoikyUddddnt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD07G95zw-SJ_12TNasN-2sG774NMYQxxQ',
    appId: '1:662979389508:ios:4684e577d3348c9feb7411',
    messagingSenderId: '662979389508',
    projectId: 'doanckuddddnt',
    storageBucket: 'doanckuddddnt.firebasestorage.app',
    iosBundleId: 'com.example.doancuoikyUddddnt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-5nu6g8-3he9KnhTi5riXe0fnMZSDbEk',
    appId: '1:662979389508:web:bf34b839dcf9ba39eb7411',
    messagingSenderId: '662979389508',
    projectId: 'doanckuddddnt',
    authDomain: 'doanckuddddnt.firebaseapp.com',
    storageBucket: 'doanckuddddnt.firebasestorage.app',
    measurementId: 'G-YNM1QE4NHF',
  );
}
